---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager.crds
  namespace: kube-system
spec:
  chart: https://cdn.w7.cc/w7panel/charts/cert-manager.crds-v1.10.1.tgz
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: w7-letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: 446897682@qq.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: w7-letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: higress